### ISSUE TITLE
Filedescriptor leak?

### ISSUE THREAD

**Issue by diorcety** [silx-kit/fabio#173] opened 2017-11-02 12:56 UTC
Is it normal that in read (tif or edf) the fd is only closed on exception?
https://github.com/silx-kit/fabio/blob/master/fabio/edfimage.py#L694

**Comment by vallsv** [comment] 2017-11-02 13:03
Yes, it is normal. It the other case, the fabio object own the file descriptor and close it when the fabio object is not anymore needed.

**Comment by diorcety** [comment] 2017-11-02 13:08
Because I have leak using 
```
    edf = fabio.edfimage.edfimage()
    edf.read(e)
```

I have to use

```
    edf = fabio.edfimage.edfimage()
    with edf._open(args.file) as e:
        edf.read(e)
```

**Comment by vallsv** [comment] 2017-11-02 13:14
Which fabio version do you use? The last release have a leak if you try to use non supported files.

The API you use is maybe not designed to be used like that.

It is better to use
```
fabio_image = fabio.open(file)
```
or 
```
with fabio.open(file) as fabio_image:
```

Why do you `read` and `_open`? To reproduce the problem? Or is that needed?

**Comment by vallsv** [comment] 2017-11-02 13:25
It looks like the `read` API is also fine. I used it for testing specific formats.

```
fabio_image = fabio.edfimage.edfimage()
fabio_image.read(e)
```

`fabio_image` own the file descriptor while the object exists.
```
# Then this should release the file descriptor
fabio_image = None
```
On the master it also exists an explicit close, now, i think
```
# Explicit close the file descriptor
fabio_image.close()
```

**Comment by diorcety** [comment] 2017-11-02 13:37
OKay that why i had the issue.
I was doing that:

>     edf = fabio.edfimage.edfimage()
>     edf.read(e)
>     # Modifications
>     edf.write(e)

**Comment by vallsv** [comment] 2017-11-02 13:51
Yes, it is not a good idea :-)

**Comment by diorcety** [comment] 2017-11-02 13:52
How do that correctly?

**Comment by vallsv** [comment] 2017-11-02 14:02
```
import fabio
filename = "foo.edf"

with fabio.open(filename) as file:
    # compute your stuff
    data = file.data / 2

header = {"Description": "Updated data divided by 2"}
file = fabio.edfimage.EdfImage(data, header)
file.write(filename)
```

Here we never erase the raw data that's very important to store original files. That's way maybe we never do this kind of things.

**Comment by vallsv** [comment] 2017-12-01 11:02
Looks to be fine then. I close the issue.

**Closed by vallsv** 2017-12-01 11:02 UTC
